#!/bin/sh

# Globals
DIRECTORY=$(pwd)

# Inputs
task=$1
args=$2

# Functions
backup() {
    # Capture the path to backup
    local path=${1:?Must provide a path to backup}
    # Create a backup path
    local backup="$path.backup"
    # Log
    echo "Backing up: $path to $backup"
    # And do the copy
    cp $path $backup
}

link() {
    # Capture paths to link
    local src=${1}
    local dest=${2}
    # Log what we're doing
    echo "Linking $src to $dest"
    # And symlink
    ln -s $src $dest
}

case "$task" in
  "shell" )
    case "$args" in
        "bash" )
            echo "Installing bash configuration"
            # Backup any files we're going to affect
            backup "$HOME/.bashrc"
            backup "$HOME/.bash_aliases"
            backup "$HOME/.bash_env"
            backup "$HOME/.bash_functions"
            # Next, remove them
            rm $HOME/.bashrc $HOME/.bash_aliases $HOME/.bash_env $HOME/.bash_functions
            # And symlink them
            link $DIRECTORY/shell/bash/bashrc $HOME/.bashrc
            link $DIRECTORY/shell/bash/aliases $HOME/.bash_aliases
            link $DIRECTORY/shell/bash/env $HOME/.bash_env
            link $DIRECTORY/shell/bash/functions $HOME/.bash_functions
            # Done
            echo "Task completed successfully";;
    esac;;
esac
